on:
  pull_request:
    types: [opened, reopened, synchronize]

name: flutter-test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.0
      - run: flutter pub get
      - run: flutter test