on:
  release:
    types: [published]

name: flutter

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - run: flutter pub get
      - run: flutter build apk --release
      - run: flutter build appbundle --release
      - name: Upload APK and AppBundle to Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: ${{ github.event.release.tag_name }}
          artifacts: build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/flutter-apk/app-release.aab